### ISSUE TITLE
Unable to use input values.

### ISSUE THREAD

**Issue by willgfx** [igor-elovikov/sd-sex#1]
Input value names are always prefixed with '#', but that conflicts with python comments; leaving me unable to use input values on my pixel processors. Maybe we can use a different symbol in expressions to refer to them?

**Comment by igor-elovikov** [comment]
Hey Will!
Could you provide a minimal example with the context where and how you want to use input names. I probably didn't fully understand the issue.

I usually use this approach:
![inputs](https://user-images.githubusercontent.com/1633230/121028267-96489a00-c79f-11eb-8f39-906878115303.png)

Then the pixel processor code:

```python
_OUT_ = get_float("#my_input")
```

you can still use # prefix inside string literals and query inputs via `get_float`

**Comment by willgfx** [comment]
Oh, that works for me. I was trying to use them like other parameters by referring to them directly.
My bad! Thanks!
